export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_FULFILLED = 'GET_TASKS_FULFILLED';
export const GET_TASKS_REJECTED = 'GET_TASKS_REJECTED';
