export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_FULFILLED = 'GET_TASKS_FULFILLED';
export const GET_TASKS_REJECTED = 'GET_TASKS_REJECTED';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_PENDING = 'ADD_TASK_PENDING';
export const ADD_TASK_FULFILLED = 'ADD_TASK_FULFILLED';
export const ADD_TASK_REJECTED = 'ADD_TASK_REJECTED';
